### ISSUE TITLE
New version of the ripper

### ISSUE THREAD

**Issue by alfablac** [NightMachinary/TGC-Ripper#1]
The Great Courses Plus updated its website. Not sure if it was coincidental, but in the middle on my process of ripping the entire library. Right now, only SD streams are wide open in the interwebz (it's possibly to get the URL by inspecting the mobile app traffic).

Desktop content is served on an unencrypted HLS stream, which is ripable by grabbing all segments from the manifest and merging it on one mp4 file. I created another script that I will soon post. Code is a mess, but I was able to grab all courses on the site. Made it on python for Xplatform support.

**Comment by capriciousduck** [comment]
Is the new script ready?

**Comment by alfablac** [comment]
@capriciousduck I never got the time to clean the code, but it's open in my repos
https://github.com/alfablac/tgc-dl

It has probably strings in my native language, lots of comments, etc
